// Emits parsed tags as HTML.
// This script assumes that the tagparser global is available.

caterwaul.clone('std seq')(function () {
  process.stdin /se[_.on('data', chunks/mb/push),
                    _.on('end',  convert_to_html),
                    _.resume()],

  where*[chunks = [],
         convert_to_html() = process.stdout.write(as_html(tagparser(chunks.join('')))),
         
         escape(s)  = s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'),
         as_html(t) = t && t.constructor === String ? escape(t) :
                      'text' in t                   ? escape(t.text) :
                      'name' in t                   ? t.metadata ? '<#{t.name} #{attrs(t.metadata)}>#{as_html(t.data)}</#{t.name}>' :
                                                                   '<#{t.name}>#{as_html(t.data)}</#{t.name}>' :
                      t instanceof Array            ? seq[~t *+as_html].join('') : 'Unknown form: #{t}',
                      
         attrs(xs)  = seq[~xs *['#{_.name}="#{_.data[0].text}"']].join(' ')]})();
// Generated by SDoc 
