// Emits parsed tags in HTML form.
// This script assumes that the tagparser global is available and that it has been preloaded with the .html() method.

caterwaul.clone('std seq')(function () {
  process.stdin /se[_.on('data', chunks/mb/push),
                    _.on('end',  convert_to_html),
                    _.resume()],

  where*[chunks = [],
         convert_to_html() = process.stdout.write(tagparser.html(chunks.join('')))]})();
// Generated by SDoc 
