// Emits parsed tags in JSON form.
// This script assumes that the tagparser global is available.

caterwaul.clone('std seq')(function () {
  process.stdin /se[_.on('data', chunks/mb/push),
                    _.on('end',  convert_to_json),
                    _.resume()],

  where*[chunks = [],
         convert_to_json() = process.stdout.write(JSON.stringify(tagparser(chunks.join(''))))]})();
// Generated by SDoc 
