// HTML adapter for the tag parser.
// This script assumes that the tagparser global is available and adds a .html() method to convert the JSON structure to HTML-like text. Because of various exceptions in the HTML format, the
// emitted code may or may not be useful.

caterwaul.clone('std seq')(function () {
  tagparser.html = convert_to_html,

  where*[convert_to_html(s) = as_html(tagparser(s)),
         
         escape(s)  = s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'),
         as_html(t) = t && t.constructor === String ? escape(t) :
                      'text' in t                   ? escape(t.text) :
                      'name' in t                   ? t.data ? t.metadata ? '<#{t.name} #{attrs(t.metadata)}>#{as_html(t.data)}</#{t.name}>' :
                                                                            '<#{t.name}>#{as_html(t.data)}</#{t.name}>' :
                                                               t.metadata ? '<#{t.name} #{attrs(t.metadata)}/>' :
                                                                            '<#{t.name}/>' :
                      t instanceof Array            ? seq[~t %[_] *+as_html].join('') : 'Unknown form: #{t}',
                      
         attrs(xs)  = seq[~xs *['#{_.name}="#{_.data[0]}"']].join(' ')]})();
// Generated by SDoc 
